"""
User API router.

Provides endpoints for user-specific operations like quota and file management.
"""

from typing import List

from fastapi import APIRouter, Depends, HTTPException

from fastapi_app.auth import get_current_user, CurrentUser
from fastapi_app.services.rate_limiter import rate_limiter, Quota
from fastapi_app.services.file_manager import file_manager, UserFile

router = APIRouter(tags=["user"])


@router.get("/quota", response_model=Quota)
async def get_quota(user: CurrentUser = Depends(get_current_user)) -> Quota:
    """
    Get current user's daily API quota.

    Returns:
        Quota object with:
        - used: Number of calls made today
        - limit: Maximum calls allowed per day (lower for anonymous users)
        - remaining: Calls remaining today

    Raises:
        401 Unauthorized if not authenticated
    """
    return await rate_limiter.check_quota(user.user_id, user.is_anonymous)


@router.get("/files", response_model=List[UserFile])
async def list_files(user: CurrentUser = Depends(get_current_user)) -> List[UserFile]:
    """
    List all files generated by the current user.

    Returns signed download URLs valid for 1 hour.

    Returns:
        List of UserFile objects sorted by creation date (newest first)

    Raises:
        401 Unauthorized if not authenticated
    """
    return await file_manager.list_files(user.user_id)


@router.get("/files/{file_id}", response_model=UserFile)
async def get_file(
    file_id: str, user: CurrentUser = Depends(get_current_user)
) -> UserFile:
    """
    Get a single file's metadata with download URL.

    Args:
        file_id: The file's UUID

    Returns:
        UserFile with download URL

    Raises:
        401 Unauthorized if not authenticated
        404 Not Found if file doesn't exist or belongs to another user
    """
    file = await file_manager.get_file(user.user_id, file_id)
    if not file:
        raise HTTPException(status_code=404, detail="File not found")
    return file


@router.delete("/files/{file_id}")
async def delete_file(
    file_id: str, user: CurrentUser = Depends(get_current_user)
) -> dict:
    """
    Delete a file from storage and database.

    Args:
        file_id: The file's UUID

    Returns:
        Success confirmation

    Raises:
        401 Unauthorized if not authenticated
        404 Not Found if file doesn't exist or belongs to another user
    """
    success = await file_manager.delete_file(user.user_id, file_id)
    if not success:
        raise HTTPException(status_code=404, detail="File not found")
    return {"success": True, "message": "File deleted"}
