"""
Auto-generated by pipeline_assembler
"""
from dataflow.pipeline import PipelineABC
from dataflow.utils.storage import FileStorage
from dataflow.serving import APILLMServing_request, LocalModelLLMServing_vllm

from dataflow.operators.agentic_rag import AgenticRAGQAF1SampleEvaluator



class RecommendPipeline(PipelineABC):
    def __init__(self):
        super().__init__()
        # -------- FileStorage --------
        self.storage = FileStorage(
            first_entry_file_name="/mnt/DataFlow/lz/proj/DataFlow-Agent/tests/test.jsonl",
            cache_path="/mnt/DataFlow/lz/proj/DataFlow-Agent/dataflow_cache",
            file_name_prefix="dataflow_cache_step",
            cache_type="jsonl",
        )
        # -------- LLM Serving (Remote) --------
        self.llm_serving = APILLMServing_request(
            api_url="http://123.129.219.111:3000/v1chat/completions",
            key_name_of_api_key="DF_API_KEY",
            model_name="gpt-4o",
            max_workers=100,
        )

        self.agentic_ragqaf1_sample_evaluator = AgenticRAGQAF1SampleEvaluator()

    def forward(self):
        self.agentic_ragqaf1_sample_evaluator.run(
            storage=self.storage.step(), input_prediction_key='refined_answer', input_ground_truth_key='golden_doc_answer', output_key='F1Score'
        )

if __name__ == "__main__":
    pipeline = RecommendPipeline()
    pipeline.compile()
    pipeline.forward()
