"""
Auto-generated by pipeline_assembler (with custom run params)
"""
from dataflow.pipeline import PipelineABC
from dataflow.utils.storage import FileStorage
from dataflow.serving import APILLMServing_request, LocalModelLLMServing_vllm

from dataflow.operators.reasoning import ReasoningAnswerGenerator, ReasoningPseudoAnswerGenerator
from dataflow.prompts.reasoning.general import GeneralAnswerGeneratorPrompt
from dataflow.prompts.reasoning.general import GeneralAnswerGeneratorPrompt



class RecommendPipeline(PipelineABC):
    def __init__(self):
        super().__init__()
        # -------- FileStorage --------
        self.storage = FileStorage(
            first_entry_file_name="/mnt/DataFlow/lz/proj/DataFlow-Agent/tests/test.jsonl",
            cache_path="/mnt/DataFlow/lz/proj/DataFlow-Agent/dataflow_cache",
            file_name_prefix="dataflow_cache_step",
            cache_type="jsonl",
        )
        # -------- LLM Serving (Remote) --------
        self.llm_serving = APILLMServing_request(
            api_url="http://123.129.219.111:3000/v1/chat/completions",
            key_name_of_api_key="DF_API_KEY",
            model_name="gpt-4o",
            max_workers=100,
        )

        self.reasoning_answer_generator = ReasoningAnswerGenerator(llm_serving=self.llm_serving, prompt_template=GeneralAnswerGeneratorPrompt())
        self.reasoning_pseudo_answer_generator = ReasoningPseudoAnswerGenerator(llm_serving=self.llm_serving, max_times=3)

    def forward(self):
        self.reasoning_answer_generator.run(
            storage=self.storage.step(),
            input_key='raw_content',
            output_key='generated_cot'
        )
        self.reasoning_pseudo_answer_generator.run(
            storage=self.storage.step(),
            input_key='generated_cot',
            output_key_answer='pseudo_answers',
            output_key_answer_value='pseudo_answer_value',
            output_key_solutions='pseudo_solutions',
            output_key_correct_solution_example='pseudo_correct_solution_example'
        )

if __name__ == "__main__":
    pipeline = RecommendPipeline()
    pipeline.compile()
    pipeline.forward()
