-- Migration: 001_initial_schema.sql
-- Description: Create usage_records and user_files tables for DataFlow-Agent
-- Created: 2025-12-27
--
-- Run this in Supabase Dashboard > SQL Editor
-- Or via: supabase db push (if using Supabase CLI)

-- ============================================
-- Table: usage_records
-- Purpose: Track daily usage per user for rate limiting
-- ============================================
CREATE TABLE IF NOT EXISTS usage_records (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    user_id UUID NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
    workflow_type TEXT NOT NULL,
    called_at TIMESTAMPTZ DEFAULT now()
);

-- Index for efficient daily count queries
-- Query pattern: COUNT(*) WHERE user_id = ? AND called_at >= TODAY_START AND called_at < TOMORROW_START
CREATE INDEX IF NOT EXISTS idx_usage_records_user_called
    ON usage_records(user_id, called_at);

-- ============================================
-- Table: user_files
-- Purpose: Track user's generated files in storage
-- ============================================
CREATE TABLE IF NOT EXISTS user_files (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    user_id UUID NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
    file_path TEXT NOT NULL,
    file_name TEXT NOT NULL,
    file_size BIGINT,
    workflow_type TEXT,
    created_at TIMESTAMPTZ DEFAULT now()
);

-- Index for listing user's files
CREATE INDEX IF NOT EXISTS idx_user_files_user_id
    ON user_files(user_id, created_at DESC);

-- ============================================
-- Comments for documentation
-- ============================================
COMMENT ON TABLE usage_records IS 'Tracks workflow API calls per user for daily rate limiting';
COMMENT ON COLUMN usage_records.workflow_type IS 'Type of workflow called: paper2figure, paper2ppt, pdf2ppt, paper2video';
COMMENT ON COLUMN usage_records.called_at IS 'Timestamp of the API call, used for daily quota calculation';

COMMENT ON TABLE user_files IS 'Tracks files generated by workflows and stored in Supabase Storage';
COMMENT ON COLUMN user_files.file_path IS 'Path in Supabase Storage: {user_id}/{timestamp}_{filename}';
COMMENT ON COLUMN user_files.workflow_type IS 'Which workflow generated this file';
