"""
Auto-generated by pipeline_assembler
"""
from dataflow.pipeline import PipelineABC
from dataflow.utils.storage import FileStorage
from dataflow.serving import APILLMServing_request, LocalModelLLMServing_vllm

from dataflow.operators.general_text import AlphaWordsFilter, ContentNullFilter, HashDeduplicateFilter, SentenceNumberFilter, SymbolWordRatioFilter



class RecommendPipeline(PipelineABC):
    def __init__(self):
        super().__init__()
        # -------- FileStorage --------
        self.storage = FileStorage(
            first_entry_file_name="/tmp/translation_sample_10.jsonl",
            cache_path="/mnt/DataFlow/lz/proj/DataFlow-Agent/cache_dir",
            file_name_prefix="dataflow_cache_step",
            cache_type="jsonl",
        )
        # -------- LLM Serving (Remote) --------
        self.llm_serving = APILLMServing_request(
            api_url="http://123.129.219.111:3000/v1/chat/completions",
            key_name_of_api_key="DF_API_KEY",
            model_name="gpt-4o",
            max_workers=100,
        )

        self.content_null_filter = ContentNullFilter()
        self.hash_deduplicate_filter = HashDeduplicateFilter(hash_func='md5')
        self.sentence_number_filter = SentenceNumberFilter(min_sentences=3, max_sentences=7500)
        self.symbol_word_ratio_filter = SymbolWordRatioFilter(threshold=0.4)
        self.alpha_words_filter = AlphaWordsFilter(threshold=None, use_tokenizer=None)

    def forward(self):
        self.content_null_filter.run(
            storage=self.storage.step(), input_key=None, output_key='content_null_filter_label'
        )
        self.hash_deduplicate_filter.run(
            storage=self.storage.step(), input_keys=None, input_key=None, output_key='minhash_deduplicated_label'
        )
        self.sentence_number_filter.run(
            storage=self.storage.step(), input_key=None, output_key='sentence_number_filter_label'
        )
        self.symbol_word_ratio_filter.run(
            storage=self.storage.step(), input_key=None, output_key='symbol_word_ratio_filter_label'
        )
        self.alpha_words_filter.run(
            storage=self.storage.step(), input_key=None, output_key='alpha_words_filter_label'
        )

if __name__ == "__main__":
    pipeline = RecommendPipeline()
    pipeline.compile()
    pipeline.forward()
